using Abstracts;
using BusinessObjects;
using BusinessObjects.Entity;
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DAL
{
    public sealed class Configuration : DbMigrationsConfiguration<ApplicationDbContext>
    {
        public Configuration()
        {
           AutomaticMigrationsEnabled = true;
          AutomaticMigrationDataLossAllowed = true;
           
            ContextKey = "DAL.ApplicationDbContext";
        }
        protected override void Seed(ApplicationDbContext context)
        {
            if (!(context.Roles.Any(it => it.Name == UserRole.Admin.ToString())))
            {
                context.Roles.AddOrUpdate(new ApplicationRole() { Name = UserRole.Admin.ToString()});
            }
            if (!(context.Roles.Any(it => it.Name == UserRole.NormalUser.ToString())))
            {
                context.Roles.AddOrUpdate(new ApplicationRole() { Name = UserRole.NormalUser.ToString()  });
            }
          if (!(context.Roles.Any(it => it.Name == UserRole.UserTest2.ToString())))
            {
                context.Roles.AddOrUpdate(new ApplicationRole() { Name = UserRole.UserTest2.ToString() });
            }
            if (!(context.Roles.Any(it => it.Name == UserRole.Company.ToString())))
            {
                context.Roles.AddOrUpdate(new ApplicationRole() { Name = UserRole.Company.ToString() });
            }
           // context.SaveChanges();
            IList<ProductDetails> defaultStandards = new List<ProductDetails>();

            //defaultStandards.Add(new ProductDetails() { Name = "DJI Phantom 4",Code= "c654c94b-3d37-47ab-abd7-4633a15b0bfa", Category="Drones",Brand="Samsung", ShortDescription = "Drona DJI PHANTOM 4 complet echipata", Description ="Camera with 1-inch 20MP sensor the onboard camera has been redesigned to use a 1-inch Megapixel CMOS sensor.Five-directions of obstacle sensing.Please refer the Instructional Video and the User Manual before use.More powerful video processing supports H.264 4K videos at 60fps or H.265 4K at 30fps, both with a 100Mbps bitrate", ReleaseDate = DateTime.Parse("11, 03 , 2017") , Model= "Big Drones", Dimensions="25 x 40 x 30", Price = 650, Image = "drona1.jpg"});
            //defaultStandards.Add(new ProductDetails() { Name = "DJI Inspire 1", Code = "8d81c75f-b000-4691-b878-3e5f532d1bb3", Category = "Drones", Brand = "Sony", ShortDescription = "Filmare 4K si fotografii de 12Mpx", Description= "The battery provides a 10-13 minutes ultra-long flying time after 60 minutes charging.Optimized for proper functionality even when the drone is out of sight. The drone is oriented in relation to the pilot. When using headless mode, the forward direction is unrelated to nose direction.", ReleaseDate = DateTime.Parse("11, 03 , 2017"), Model = "Big Drones", Dimensions = "25 x 40 x 30", Price = 7000, Image = "drona2.jpg" });
            //defaultStandards.Add(new ProductDetails() { Name = "Parrot Bepop", Code = "124db400-e863-426b-9a07-b85071e744fa", Category = "Drones", Brand = "Sony", ShortDescription = "Drona cu Gimbal 3D si camera 4K.",Description= "Resulting from two years of design, the Parrot Bebop 2 is your ideal flight companion. Weighing 500 g and offering 25 minutes of autonomous flight time, this leisure drone is cutting-edge. Its high-performance specs mean it can fly, film, and take photographs brilliantly both indoors and outdoors", ReleaseDate = DateTime.Parse("11, 03 , 2018") , Model = "Small Drones", Dimensions = "10 x 10 x 30", Price = 300, Image = "drona3.jpg" });
            //defaultStandards.Add(new ProductDetails()  { Name = "EOS 600D", Code = "41ef02eb-8d41-45e7-8c5a-67cf8d1cb353",  Category = "Cameras", Brand = "Canon", ShortDescription = "With class-leading 18-megapixel resolution",  Description = "Shoot Full - HD video with manual control over frame rate, exposure and sound.Video Snapshot technology allows short clips of 2, 4 or 8 sec to be merged into a single movie file, for footage that looks like it was edited professionally, while Movie Digital Zoom permits 3 - 10x magnification.", ReleaseDate = DateTime.Parse("6, 04 , 2018"), Model ="DSLR", Dimensions = "5.2 x 3.9 x 3.1", Price = 400, Image = "camera1.jpg" });
            //defaultStandards.Add(new ProductDetails() { Name = "EOS 5D", Code = "56da5e82-31c0-4e65-8969-9880e5ffb8fe", Category = "Cameras", Brand = "Canon", ShortDescription = "Stunning performance and advanced AF system", Description = "Canon's EOS 5D series of cameras has a rich heritage – the original EOS 5D bought full-frame photography to the masses, the Mark II unleashed Full HD video capture for the first time on a DSLR, and while the Mark III became a firm favourite amongst photographers. The EOS 5D Mark IV pretty much tweaks and improves on everything before it, with a new 30.4MP sensor and advanced 61-point AF system. A brilliant DSLR that was until recently our top pick, but the arrival of the D850 means it slips a place down to number two", ReleaseDate = DateTime.Parse("4 , 05 , 2018") , Model = "DSLR", Dimensions = "5.2 x 3.9 x 3.1", Price = 700, Image = "camera2.jpg" });
            //defaultStandards.Add(new ProductDetails() { Name = "EOS 80D", Code = "8389b7d0-4a25-4d94-99b2-f7531051c70f", Category = "Cameras", Brand = "Canon", ShortDescription= "Canon's high-end enthusiast DSLR", Description = "The EOS 80D is Canon's high-end enthusiast DSLR and while it might be getting on a bit, is still a great buy. It features a fast and effective 45-point autofocusing system, while the clever Dual Pixel CMOS AF system for Live View shooting delivers snappy focusing speeds. The camera's handling is excellent, promoting creative shooting as well as making setting adjustments quick and easy. It also has a high quality 24.2MP sensor that is able to capture a good level of detail while keeping noise under control. A great enthusiast DSLR that packs a decent performance.", ReleaseDate = DateTime.Parse("19, 03 , 2017") , Model = "DSLR", Dimensions = "5.2 x 3.9 x 3.1", Price = 930, Image = "camera3.jpg" });
            //defaultStandards.Add(new ProductDetails() { Name = " EOS 800D", Code = "da34db8a-0edc-4c18-9384-99f4a7661687", Category = "Cameras", Brand = "Canon", ShortDescription = "Perfect for the action photographer", Description = "Costing a bit more than the Nikon D3400, but offering quite a bit more in the way of features, the Canon EOS Rebel T7i (known as the EOS 800D outside the US) is a great entry-level DSLR. The new sensor impresses, as does the 45-point autofocus system backed up by excellent live view AF, while the newly designed graphical interface will certainly make this camera even more appealing to new users. The absence of 4K video and the quality of the exterior materials disappoint, but this aside, if you're looking for a well-rounded and easy to use camera for your first DSLR the EOS Rebel T7i / EOS 800D is certainly a very good bet.", ReleaseDate = DateTime.Parse("11 , 02 , 2017") , Model = "DSLR", Dimensions = "5.2 x 3.9 x 3.1", Price = 660, Image = "camera4.jpg" });
            defaultStandards.Add(new ProductDetails() { Name = "D3400", Code = "ced8a650-30d5-4602-8945-9e0fd525d7dc", Category = "Cameras", Brand = "Nikon", ShortDescription = "D3400 is basic but brilliant", Description = "Sensor: APS-C CMOS | Megapixels: 24.2MP | Autofocus: 11-point AF, 1 cross-type | Screen type: 3.0-inch, 921,000 dots | Maximum continuous shooting speed: 5fps | Movies: 1080p | User level: Beginner", ReleaseDate = DateTime.Parse("7, 03 , 2018") , Model = "DSLR", Dimensions = "5.2 x 3.9 x 3.1", Price = 400, Image = "camera5.jpg" });
            //defaultStandards.Add(new ProductDetails() { Name = "A330", Code = "7f49f379-2f98-4e8b-9545-1630844e44c6", Category = "Cameras", Brand = "Sony", ShortDescription = "Camera with Super SteadyShot ", Description = "Featuring a 10.2MP CCS sensor, the A330 is an unremarkable upgrade to the A300 with a tiltable LCD screen and Sony's unique Quick AF Live View. A new Graphic User Interface (GUI) makes it slightly more user-friendly than its predecessor", ReleaseDate = DateTime.Parse("18, 05 , 2018") , Model = "DSLR", Dimensions = "5.2 x 3.9 x 3.1", Price = 450, Image = "camera6.jpg" });
            //defaultStandards.Add(new ProductDetails() { Name = "Dell XPS 13", Code = "832aa3a1-2763-4ea3-ad7c-ae30aa113284", Category = "Computers", Brand = "Dell", ShortDescription = "One of the best laptops ever made", Description = "Although the Dell XPS 13 has been knocked into second place by the excellent MateBook Pro X, it is still an absolutely brilliant laptop. There's a good reason why it was at the top of our best laptops list for three years running. The 2018 Dell XPS 13 is a slimmer, more powerful version of the award-winning laptop with a stunning 4K display and a gorgeous Rose Gold on Alpine White color option. Packing an 8th-generation Intel Core i5 or i7 CPU and a bezel-less ‘Infinity Edge’ display, this Dell XPS 13 is more expensive, but its still worth every penny. It’s no wonder the Dell XPS 13 continues to be the most popular Windows laptop in the world. Better yet, there’s a wide range of customization options, so you can make the Dell XPS 13 the best laptop for you.", ReleaseDate = DateTime.Parse("7, 02 , 2018"), Model = "Laptop", Dimensions = "33.02 x 20.32 x 39.62", Price = 800, Image = "laptop1.jpg" });
            //defaultStandards.Add(new ProductDetails() { Name = "Asus Chromebook Flip", Code = "d38302eb-e31a-4180-994b-cf1a7e37b895", Category = "Computers", Brand = "Asus", ShortDescription = "Tactile keyboard and elegant tablet mode", Description = "When it comes to the best Chromebook laptop, you have a choice between two stark alternatives. There's the premium Chromebook Pixel, which we list further down this page, and then there's the excellent Asus Chromebook Flip C302, which combines premium features in a much more affordable package. For many people, Chromebooks are excellent and affordable laptops that are perfect for students, and the Asus Chromebook Flip C302 is easily one of the best Chromebooks, and one of the best laptops, money can buy. It comes with an Intel Core processor, full 1080p display, touchscreen, backlit keyboard and USB-C port.", ReleaseDate = DateTime.Parse("23, 04 , 2018"), Model = "Laptop", Dimensions = "33.02 x 20.32 x 39.62", Price = 400, Image = "laptop2.jpg" });

            //defaultStandards.Add(new ProductDetails() { Name = "Samsung Notebook 9", Code = "e38873a5-0c4d-48b6-af39-f03dc28c9253", Category = "Computers", Brand = "Samsung", ShortDescription = "The dawn of a new era for 2-in-1 laptops ", Description = "The Samsung Notebook 9 is what other 2-in-1 laptops have aspired to be since their conception. It hones in on the S-Pen, Samsung’s own proprietary stylus with 4,096 levels of pressure sensitivity (the same as Microsoft’s new Surface Pen), a nifty little accessory that conveniently doesn’t require charging. Although the touchscreen display is only 1080p, at between 350 and 450 nits of brightness, you won’t be paying any mind to the pixels, or lack thereof. Plus, the lengthy battery life more than makes up for this hybrids few setbacks.", ReleaseDate = DateTime.Parse("18, 07 , 2018"), Model = "Laptop", Dimensions = "33.02 x 20.32 x 39.62", Price = 500, Image = "laptop3.jpg" });
            //defaultStandards.Add(new ProductDetails() { Name = "Asus Chromebook Flip", Code = "d4c2aa4a-a295-462c-90fc-6c811b5804fc", Category = "Computers", Brand = "Asus", ShortDescription = "Gorgeous, vivid screen", Description = "In a lot of ways, the Asus Chromebook Flip C302 is a sort of apology for the Google Chromebook Pixel that came before. And, even while the Google Pixelbook looms in the background with its thousand dollar price tag, the Asus Chromebook is the best Chromebook for the money. The Asus Chromebook Flip cuts the Pixelbook’s price in half while retaining the 360-degree hinge that basically makes it a 2-in-1 laptop, but with Android apps. And, when it comes to build quality, you can experience style that rivals the MacBook Pro, without spending the cash for a MacBook Pro. ", ReleaseDate = DateTime.Parse("7, 09 , 2018"), Model = "Laptop", Dimensions = "33.02 x 20.32 x 39.62", Price = 440, Image = "laptop4.jpg" });
            //defaultStandards.Add(new ProductDetails() { Name = "Acer Aspire E15", Code= "b89117cc-c5c7-42ff-b038-fb50330535d2", Category= "Computers", Brand= "Acer", ShortDescription = "Acer Aspire E15", Description = "While it might not win any beauty contests, the Acer Aspire e15 does one thing, and it does it well: work. If you need a laptop that you can carry with you between classes and get some work done, without needing to break open the piggy bank, this laptop will go a long way. Rocking one of the new 8th-generation Coffee Lake U-series CPUs, you’ll never have to worry about your laptop holding back your studying. Just don’t expect a chassis you can proudly display in the coffee shop.", ReleaseDate = DateTime.Parse("1, 03 , 2018") , Model= "Laptop", Dimensions="25 x 40 x 30", Price = 650, Image = "laptop5.jpg"});
            //defaultStandards.Add(new ProductDetails() { Name = "Samsung Notebook 7 Spin", Code= "f26151a7-565a-4941-8499-f5c73f75987a", Category= "Computers", Brand= "Samsung", ShortDescription = "Long battery life", Description = "While we still adore the Samsung Notebook 7 Spin, we have to admit that it’s not quite the same device it used to be. Instead, it’s a 13-inch convertible laptop that literally bends over backwards to suit your creative needs. And, while you won’t find an included stylus in sight, nor are discrete graphics present in this year’s model, the lengthy battery life and punchy processor nearly makes up for any concessions.", ReleaseDate = DateTime.Parse("11, 03 , 2017") , Model= "Laptop", Dimensions="25 x 40 x 30", Price = 650, Image = "laptop6.jpg"});
            //defaultStandards.Add(new ProductDetails() { Name = "Galaxy S9 Plus", Code= "48a895b9-5d94-4648-b869-36a7a41ea405", Category="Mobile Phone",Brand="Samsung", ShortDescription = "The best smartphone around", Description = "Screen: The Super AMOLED 6.2-inch display has been measured as one of the very best around right now, with super colours, great dynamic range and, essentially, the very best viewing experience you can have on a mobile phone.Battery life: The battery life on the S9 Plus is better than that seen on the smaller S9,  thanks to the 3, 500mAh battery in the Plus model - although it's probably the weakest part of the phone, not offering as much life as we'd have liked.", ReleaseDate = DateTime.Parse("11, 03 , 2017") , Model= "Android", Dimensions= "5.81 x 2.7 x 0.33", Price = 380, Image = "phone1.jpg"});
            //defaultStandards.Add(new ProductDetails() { Name = "Apple iPhone X", Code= "66cf57b8-7df0-4036-bf59-e9a0ff851082", Category= "Mobile Phone", Brand= "Apple", ShortDescription = "Stunning screen and face ID", Description = "The iPhone X is not only the best smartphone Apple has released to date; it’s also the most expensive, setting customers back £999 for the 64GB base model. But it’s well worth it. Performance is fantastic, as are the images produced by the dual-camera setup, and Face ID is (honestly) the best thing since sliced bread", ReleaseDate = DateTime.Parse("9, 10 , 2017") , Model= "iOS", Dimensions= "5.65 x 2.79 x 0.3", Price = 650, Image = "phone2.jpg"});



            foreach (ProductDetails product in defaultStandards)
                context.Product.AddOrUpdate(it => it.Code, product);

            //context.Drones.AddOrUpdate(it=>it.Id , new Drone() { Id = 15, Name = "Drona Cinestar", Description = "Drona Cinestar 8 reprezinta cel mai performant echipament pentru filmare aeriana cu capacitate maxima de ridicare.", Price = 650 });
            context.SaveChanges();
            base.Seed(context);
        }
    }
}
